if(DEFINED VCPKG_GLOBAL_TOOLCHAIN_FILE)
    message(STATUS VCPKG_GLOBAL_TOOLCHAIN_FILE: ${VCPKG_GLOBAL_TOOLCHAIN_FILE})
    include(${VCPKG_GLOBAL_TOOLCHAIN_FILE})

    # set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${VCPKG_GLOBAL_TOOLCHAIN_FILE}")
endif()

include_directories("${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include") 
include("${CMAKE_CURRENT_LIST_DIR}/zig_toolchain_base.cmake")